enforce_secure_profile: false
listeners:
- query_port: 25565
  motd: '&6*&b-&6*&b-&6*&b-&6*&b-&6*&b-&6*&b-&6*&b-&6*&b-&6*&b- &d&lREDE  GALAXY &b-&6*&b-&6*&b-&6*&b-&6*&b-&6*&b-&6*&b-&6*&b-&6*&b-&6*
    &6&l| &eSurvival &6&l|&e loja.redegalaxy.space &6&l| &eSlimeFun &6&l|'
  tab_list: GLOBAL_PING
  query_enabled: false
  proxy_protocol: false
  forced_hosts:
    pvp.md-5.net: pvp
  ping_passthrough: false
  priorities:
  - survival
  bind_local_address: true
  host: 0.0.0.0:25577
  max_players: 1
  tab_size: 60
  force_default_server: false
remote_ping_cache: -1
network_compression_threshold: 256
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
  - bungeecord.command.kick
  - nlogin.admin
log_pings: true
connection_throttle_limit: 3
server_connect_timeout: 5000
timeout: 30000
stats: c3d54cf5-d0bc-4a0a-9cf4-e197bc168ae2
player_limit: -5
ip_forward: true
groups:
  iTakinn:
  - admin
remote_ping_timeout: 5000
connection_throttle: 4000
log_commands: false
prevent_proxy_connections: false
online_mode: false
forge_support: false
disabled_commands:
- disabledcommandhere
servers:
  lobby:
    motd: '&1Just another BungeeCord - Forced Host'
    address: localhost:25565
    restricted: false
  survival:
    motd: '&1Just another BungeeCord - Forced Host'
    address: localhost:25565
    restricted: false
